apiVersion: v1
kind: ConfigMap
metadata:
  name: html-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>GitOps Hello World</title>
    </head>
    <body>
        <h1>¡Hola Mundo desde GitOps!</h1>
        <p>Esta es una aplicación desplegada con GitOps en Kubernetes usando ArgoCD.</p>
    </body>
    </html>
